name: Production Build
on:
  push:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Deploy to ZEIT Now
      run: curl https://api.zeit.co/v1/integrations/deploy/QmeRaZ4pTnHNyskt8jdFDFzpJqqRQdaCuxvb6xk5cppDHG/QTntAq8kz8
